### ISSUE TITLE
Library cannot be imported 

### ISSUE THREAD

**Issue by armend26** [feihoo87/waveforms#2]
I'm trying to import and test the library ,but the following log appears. 

```
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\waveforms\cache.py:13: UserWarning: portalocker not installed, cache will not be thread safe!
  warnings.warn('portalocker not installed, cache will not be thread safe!')
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from waveforms import *
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\waveforms\__init__.py", line 4, in <module>
    from .quantum import (Config, compile, getConfig, libraries, qpt, qptInitList,
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\waveforms\quantum\__init__.py", line 1, in <module>
    from ..qlisp.simulator import applySeq, regesterGateMatrix, seq2mat
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\waveforms\qlisp\__init__.py", line 12, in <module>
    from .prog import Program, ProgramFrame
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\waveforms\qlisp\prog.py", line 10, in <module>
    from waveforms.scan_iter import StepStatus
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\waveforms\scan_iter.py", line 266, in <module>
    vars: list[tuple[str]], filter: Callable[..., bool] | None,
TypeError: unsupported operand type(s) for |: '_CallableGenericAlias' and 'NoneType'
```

Does anyone have any suggestions for solving this problem?

**Comment by feihoo87** [comment]
The latest version required python >= 3.10.
